language: python
python:
  - "2.5"
  - "2.6"
install:
  - ls -Al
  - python -c 'import docutils; print(docutils.__version__)' || true
  - python -c 'import pygments; print(pygments.__version__)' || true
  - python -c 'import jinja2; print(jinja2.__version__)' || true
  - python setup.py install
  - echo '# jinja2 does not get updated by 2to3 when installing under'
  - echo '# Python 3.x via setup.py. Fixed by forced reinstall.'
  - pip -v install --use-mirrors --force-reinstall jinja2
  - # need simplejson for python<=2.5 
  - python -c 'import sys; sys.version_info[:2] <= (2, 5) or sys.exit(1)' || pip install --use-mirrors simplejson

script:
  - echo '# package versions'
  - python -c 'import docutils; print(docutils.__version__)' || true
  - python -c 'import pygments; print(pygments.__version__)' || true
  - python -c 'import jinja2; print(jinja2.__version__)' || true
  - echo
  - echo '# building sphinx/doc'
  - ( cd doc && sphinx-build -b html . _build | cat ) || true
  - echo '# building sphinx/doc [done]'
  - echo
  - echo '# running sphinx/tests'
  - make test TEST=' -v '
  - echo '# running sphinx/tests [done]'
