language: python
python:
  - "2.7"
  - "3.2"
env:
  - DEP_DOCUTILS='docutils>=0.7'
  - DEP_DOCUTILS='svn+http://docutils.svn.sourceforge.net/svnroot/docutils/trunk/docutils'

install:
  - pip install -v --use-mirrors "$DEP_DOCUTILS"
  - pip install -v --use-mirrors .

script:
  - echo '# package versions'
  - python -c 'import docutils; print(docutils.__version__)'
  - python -c 'import jinja2; print(jinja2.__version__)'
  - python -c 'import pygments; print(pygments.__version__)'
  - python -c 'import sphinx; print(sphinx.__version__)'
  - echo '# building sphinx/doc'
  - ( cd doc && sphinx-build -W -b html . _build/html | cat )
  - echo '# building sphinx/doc [done]'
  - echo
  - echo '# running sphinx/tests'
  - make test TEST=' -v '
  - echo '# running sphinx/tests [done]'

matrix:
  exclude:
    - python: "3.2"
      env: DEP_DOCUTILS='docutils>=0.7'
