language: python
python:
  - "2.7"
  - "3.2"
  - "3.1"
install:
  - python setup.py install
script:
  - python -c 'import docutils; print(docutils.__version__)' || true
  - python -c 'import jinja2; print(jinja2.__version__)' || pip install --upgrade --use-mirrors jinja2
  - python -c 'import pygments; print(pygments.__version__)' || true
  - make check || true
  - ( cd doc && sphinx-build -b html . _build | cat ) || true
  - make test TEST=' -v '
