language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
install:
  - ls -Al
  - python -c 'import docutils; print(docutils.__version__)' || true
  - python -c 'import pygments; print(pygments.__version__)' || true
  - python -c 'import jinja2; print(jinja2.__version__) || true
  - # jinja2 does not get updated by 2to3 when installing under 
  - # Python 3.x via setup.py. Fixed by forced reinstall.
  - pip -v install --use-mirrors --force-reinstall jinja2
script:
  - echo '# package versions'
  - python -c 'import docutils; print(docutils.__version__)' || true
  - python -c 'import pygments; print(pygments.__version__)' || true
  - python -c 'import jinja2; print(jinja2.__version__)' || true
  - echo
  - echo '# building sphinx/doc'
  - ( cd doc && sphinx-build -b html . _build | cat ) || true
  - echo '# building sphinx/doc [done]'
  - echo
  - echo '# running sphinx/tests'
  - make test TEST=' -v '
  - echo '# running sphinx/tests [done]'
