language: python
python:
  - "2.5"
install:
  - python -c 'import sys; sys.exit(sys.version_info[:2] <= (2, 5))' && pip install -v --use-mirrors simplejson
  - pip install --use-mirrors .
  - echo '# package versions'
  - python -c 'import docutils; print(docutils.__version__)'
  - python -c 'import pygments; print(pygments.__version__)'
  - python -c 'import jinja2; print(jinja2.__version__)'

script:
  - echo '# building sphinx/doc'
  - ( cd doc && sphinx-build -b html . _build | cat ) || true
  - echo '# building sphinx/doc [done]'
  - echo
  - echo '# running sphinx/tests'
  - make test TEST=' -v '
  - echo '# running sphinx/tests [done]'
